name: Deploy Coze App to GitHub Pages

on:
  push:
    branches:
      - main  # 或者您的主分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip the code
        run: |
          # 假设您的压缩包名为 code.zip
          unzip riyulianxi.zip -d ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
