name: Deploy Coze App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and unzip code
        run: |
          # 查找第一个zip文件并解压
          ZIP_FILE=$(find . -name "*.zip" -type f | head -1)
          if [ -n "$ZIP_FILE" ]; then
            echo "Found zip file: $ZIP_FILE"
            mkdir -p ./temp_extract
            unzip "$ZIP_FILE" -d ./temp_extract
            echo "Contents after unzip:"
            find ./temp_extract -type f | head -20
          else
            echo "No zip file found!"
            exit 1
          fi

      - name: Organize files for deployment
        run: |
          mkdir -p ./dist
          
          # 查找index.html文件的位置
          INDEX_FILE=$(find ./temp_extract -name "index.html" -type f | head -1)
          
          if [ -n "$INDEX_FILE" ]; then
            # 获取index.html所在的目录
            SOURCE_DIR=$(dirname "$INDEX_FILE")
            echo "Found index.html in: $SOURCE_DIR"
            
            # 将该目录下的所有文件复制到dist
            cp -r "$SOURCE_DIR"/* ./dist/
            
            echo "Files copied to dist:"
            ls -la ./dist/
          else
            echo "No index.html found!"
            echo "Available HTML files:"
            find ./temp_extract -name "*.html" -type f
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
